### ISSUE TITLE
NuxtJS as a higherlevel framework

### ISSUE THREAD

**Issue by ExXTreMe315** [Stuyk/rebar-altv#134]
Hey I kinda love rebar.
But I got a short question. Is it possible to upgrade the build in VueJS to use NuxtJS as a higherlevel framework?

greetings
ExXTreMe

**Comment by Stuyk** [comment]
No, NuxtJS has a lot of useless functionality for an alt:V server. Plus it can't support a lot of the built-in functionality that is provided by NuxtJS. An example being the server-side API system it has.

**Comment by ExXTreMe315** [comment]
Thats true xD.
Thankes a lot...
