### ISSUE TITLE
App.vue - Cannot find module

### ISSUE THREAD

**Issue by KoronGIT** [Stuyk/rebar-altv#136]
In webview->src->app.vue it says "import DevelopmentBar from './components/Development.vue';" but it doesn't exist.

![2024-07-29 09_30_17-Window](https://github.com/user-attachments/assets/861cbc89-42e8-4056-b390-097853f482c5)

**Comment by KooperNinja** [comment]
Solution: Use the Vue.Volar Extension and uninstall the Vetur Extension.
