### ISSUE TITLE
Plugin category

### ISSUE THREAD

**Issue by simas727** [Stuyk/rebar-altv#142]
would love if it would be posible like fivem to categorize plugins
[UI]
[JOB]
[EXTRA]
i think it would be great i love current plugins system but if we can categorize plugins it could be awesome

**Comment by floydya** [comment]
Categorize where? 
Folder structure like: `src/plugins/JOB/driver/server/index.ts`?
Or categorize them in the plugins discord channel?
Idk how it is implemented in five, but it'll make more sense if you explain it here.

**Comment by MnkyArts** [comment]
I created a Pull request of how it could work. Feedback and suggestions for improvement are welcome.
https://github.com/Stuyk/rebar-altv/pull/145
