### ISSUE TITLE
 function useweapon bug，

### ISSUE THREAD

**Issue by kobo07** [Stuyk/rebar-altv#147]
/**
     * Save current player weapons
     */
    function save() {
        const document = Rebar.document.character.useCharacter(player);
        if (!document.get()) {
            return;
        }

        const ammo: { [key: string]: number } = {};
        for (let weapon of player.weapons) {
            ammo[weapon.hash] = player.getAmmo(weapon.hash);
        }

        document.setBulk({
            weapons: player.weapons,
            ammo: ammo,
        });
    }
    
    player.getAmmo(weapon.hash) not work, the hash should be the ammohash,not weapon hash...
    
    getweaponhash is ok..

**Comment by Stuyk** [comment]
Can you elaborate on this more?
