### ISSUE TITLE
Dependencies for tailwind.config.js file

### ISSUE THREAD

**Issue by Kripteks** [Stuyk/rebar-altv#154]
Hi,

I am looking for a way to add dependencies to the tailwind.config.js file in the webview folder. Technically I can do this, but when I use the `pnpm run rebar:upgrade` command, the changes I make will be lost. Can you think of a way to prevent this for webviews?

But this is what I am trying to add; https://www.shadcn-vue.com/docs/installation/vite.html

I hope I explained what I mean.

**Comment by Stuyk** [comment]
As others have said in Discord, doing proper merging via upstream with git will prevent the files you don't want changed from being changed. This is the correct solution to the problem. `rebar:upgrade` is for the developers who have yet to learn how to use git and allows for people who like to tinker to push forward without worrying about their tools.

If you want more customization in regards to ui changes such as integrating `shadcn` then you'll have to use `git` mixed with merging from upstream. It's just as easy as `rebar:upgrade`.
