### ISSUE TITLE
Feat/Req: Asset folder (Image folder to asset?)

### ISSUE THREAD

**Issue by MnkyArts** [Stuyk/rebar-altv#84]
It would be great to get somekind of asset folder where we could put fonts (and other assets) which gets used by like for example alt.TextLabels. (Dont think we have something like this?). Maybe even just renaming images to assets (or something else) and have the possibility to add more stuff in there? Don't know how necessary another folder is

**Comment by oxince** [comment]
You can just create it urself.

**Comment by MnkyArts** [comment]
> You can just create it urself. But anyways i would recommend an assets server.

@oxince 
Well obv i can create it myself, but we have already an image folder so why not asset. And afaik a cdn wont work for alt.TextLabel as it needs it local.
