### ISSUE TITLE
Enhancement: Validate Group permission against Vehicle System

### ISSUE THREAD

**Issue by Booster1212** [Stuyk/rebar-altv#92]
Add a way to validate current bound permission from groups Array against some kind of vehicle permissions, add new functions for toggleEngine/Doors/Locks as well.

**Comment by Booster1212** [comment]
- Comment: Might not even new functions for that stuff, may it can be param: bool i.e.

isGroup?: boolean; for the already existing functions.

**Comment by phederal** [comment]
Nice idea

**Comment by Booster1212** [comment]
This is not neccessary. I've built a workaround which utilizes vehicle keys, based on faction ranks.
