### ISSUE TITLE
Door System

### ISSUE THREAD

**Issue by Stuyk** [Stuyk/rebar-altv#98]
Athena still has a really good door system for managing doors, I want to port it over with virtual entities.

**Comment by MnkyArts** [comment]
Would be great to somehow have the Permission System integrated!

**Comment by floydya** [comment]
Do we need that as part of rebar or a standalone plugin?

**Comment by MnkyArts** [comment]
> Do we need that as part of rebar or a standalone plugin?

I think this would be a great addition as a controller. I feel like stuff like this are always usefull in a Framework like Rabar.

**Comment by Stuyk** [comment]
It'll be a controller for sure.

**Comment by floydya** [comment]
Created a draft: #128 , feel free to check and leave some comments around implementation.
It is basically a copy of Athena's door system, but with small improvements around string lock state in database.
